jekyll-theme-NAME: cayman
title: DSC180B Final Project
description: Documentation for the DSC180B Final Project - NBA Shot Defense Analysis
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cadenpascual.github.io/DSC180B_FinalProject"
github_repository: "NBA-Defensive-dna"